name: Homoto
favicon: null
layout_spectrum: 0.6998185457196087
typography_spectrum: 0.7154754365328699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9667442056816071
  lightness: 0.3634945647791028
  saturation: 0.13254452496767044
  rhythmicContrast: 0.9653402934782207
purpose: []
